### PR TITLE
error handling and refactoring across backend

### PR DESCRIPTION
**Pull request by dscottd7**
This adds error-handling throughout the backend, hopefully in a consistent manner.

There's also a bit of refactoring and clean-up from the "experimental" early state of the code.

### CODE REVIEW

**Review by superhermione — COMMENTED** [review]
I tested on swagger as well as frontend with your implemented changes. It looks cleaner for sure, yet I do like when I was able to visually view response body in terminal which helps me debug faster. However, if this is a better practice, I will agree on the majority decision by the team.

**Comment by dscottd7** [comment]
@superhermione – I updated so logging info is printed to console. Can you try this out?

**Comment by jbh14** [comment]
@dscottd7 I reviewed this tonight, and love what you've done - very clean and tidy, nice work.  The logging is consistent and displays to me in the terminal (like a print statement would) in a useful way.

One suggestion, especially since you noted this is currently not working.  Can "**/openai-test**" be modified to simply send a very simple completion request to OpenAI (don't accept URLs or attempt to do any scraping, or simply accept a text prompt like "What is the capital of Alaska")?  

That endpoint was handy to me in validating that an OpenAI key was properly stored as an environmental variable when deploying as a Docker image to Google Cloud Run.  The other routes nicely compliment it in terms of testing scraping and then our actual end-to-end operating (scrape and send to OpenAI), so I think that's a logical thing to set up that endpoint to do.

Let me know if you object or would like to me incorporate that after merging this PR, just my 2 cents.  Otherwise, I think this is good to go!

**Comment by jbh14** [comment]
Approving - will keep changes from "endpoints" from https://github.com/dscottd7/quibble-backend/pull/27/commits in main

**Pull request merged**
