### PR TITLE
Improve scraping

### PR DESCRIPTION
**Pull request by dscottd7**
Made changes to Selenium implementation to increase the number of sites we can scrape:

- switched to `undetected_chromedriver` which is designed for avoiding bot detection
- added visit to google.com prior to user-submitted URLs
- added more simulated human interactions (scrolling, delays)
- added viewports
- added more error tracing

This should work for the /scrape route and all of the various /compare routes we have going.

New sites that should now work:

- https://www.nordstromrack.com/s/fjallraven-knken-water-resistant-backpack/3833666
- https://www.altrarunning.com/en-us/road/mens-torin-7/AL0A82C4.html

Sites that still don't work:

- https://www.wayfair.com/Cuisinart--Cuisinart-500-Watt-Countertop-Blender-BFP703BC-L811-K~CUI3403.html
- https://www.walmart.com/ip/Apple-AirPods-3rd-Generation/5527780373

### CODE REVIEW

**Review by dscottd7 — COMMENTED** [review]
@jbh14 This update to README looks good to me.

**Comment by jbh14** [comment]
Worked great with updated README steps and following Scott's recommendation to ensure certificate is set up for Python 3.11: `/Applications/Python\ 3.11/Install\ Certificates.command`

**Review by jbh14 — APPROVED** [review]
See comments in PR history - this is working great for me, so approving.

**Review by edwmai — APPROVED** [review]
Added a command in the readme to create and activate a virtual environment on windows

**Review by superhermione — CHANGES_REQUESTED** [review]
I tested this branch locally. When I ran the server, I had an error like this: 
image 
This shows that my local environment lacks distutils dependency. 
So, I had to add "setuptools>=58.0.0" into requirements.txt and the backend app was able to run.  @dscottd7 @jbh14 @edwmai  I don't know if it's my machine's setting or you had the similar problem. If you encounter the same distutils error, I suggest that we add  "setuptools>=58.0.0" into requirements.txt. 

Otherwise, Nordstorm link and Altrarunning link are able to be compared.

**Comment by dscottd7** [comment]
> I tested this branch locally. When I ran the server, I had an error like this: image This shows that my local environment lacks distutils dependency. So, I had to add "setuptools>=58.0.0" into requirements.txt and the backend app was able to run. @dscottd7 @jbh14 @edwmai I don't know if it's my machine's setting or you had the similar problem. If you encounter the same distutils error, I suggest that we add "setuptools>=58.0.0" into requirements.txt.
> 
> Otherwise, Nordstorm link and Altrarunning link are able to be compared.

@superhermione This error is related to the version of Python you are running on your machine. We updated the README to say you should be running Python 3.11 for this app to work because `undetected_chromedriver` uses a package that was deprecated in Python 3.12. That said, I did add `setuptools` to `requirements.txt` because adding it doesn't seem to break anything. You should be able to run this locally now.

**Review by superhermione — APPROVED** [review]

**Pull request merged**
