### PR TITLE
fix for failing async chrome driver on attempt 1

### PR DESCRIPTION
**Pull request by dscottd7**
This just adds a delay before the drivers quit to ensure that both concurrent chrome drivers complete the scrape

### CODE REVIEW

**Comment by jbh14** [comment]
Local testing:
- scrape on "https://www.nordstromrack.com/s/fjallraven-knken-water-resistant-backpack/3833666" > appears to work great
- testing compare from locally running frontend on that product vs an ebay backpack > appears to be working!  from my logs, it looks like this successfully retried and worked: 
<img width="835" alt="Screenshot 2024-11-27 at 10 28 33 AM" src="https://github.com/user-attachments/assets/94b11bbe-7d01-4405-b12b-cc9c8d14fab7"

**Comment by jbh14** [comment]
Built new docker image (jbh14/quibble-backend:1.3.2) for this and redeployed to cloud:
- tested scraping of "https://www.nordstromrack.com/s/fjallraven-knken-water-resistant-backpack/3833666" > works great
- tested comparing that product to ebay backpack from deployed frontend > getting the following error.  Note that even when switching the order of the URLs, the error lists on URL2 every time:
Screenshot 2024-11-27 at 10 53 38 AM

Looking into the logs for the backend (https://console.cloud.google.com/run/detail/us-central1/quibble-backend/logs?authuser=1&inv=1&invt=Abinsg&project=quibble-backend), it seems like both "scrape" attempts are failing, and a 500 error is being returned, indicating a ChromeDriver issue.
Screenshot 2024-11-27 at 10 56 04 AM

**Comment by dscottd7** [comment]
@jbh14 – Okay, I ended up doing major surgery to get_with_selenium.py. Making it headless is a simple, one-line addition. But the chrome drivers were still not running concurrently. After tons and tons of debugging the failing chrome driver errors and doing some research, I found out that WebDriver instances are not thread-safe, so there was a race condition happening where the shared driver resources in selenium_pool were conflicting with one another while running simultaneously. You could see this happening in the browsers that popped up when it wasn't headless – two would open and they'd both close at the same time. Then the second URL would reopen in a third browser window (effectively defeating the concurrency). The solution to keeping this concurrent was to create separate WebDriver instances for each URL, which ultimately eliminates the need for creating a pool of drivers (and selenium_pool.py). I think this may be more wasteful in terms of resources, but it's the only way I could find to get them to be async and concurent. Anyway, it does seem faster now. And it should be headless and work in Google Cloud Run.

**Comment by jbh14** [comment]
@dscottd7 , just rebuilt the image and deployed, looking great!  
Screenshot 2024-11-29 at 3 35 12 PM

I just committed a minor change to build the docker image with Python 3.13, since we are now listing "setuptools>=58.0.0" in our requirements.  The docker image I built/deployed (quibble-backend:1.4.2) uses that.

**Review by edwmai — APPROVED** [review]
Functionalities are still the same with the changes.

**Pull request merged**
