### PR TITLE
Route to call openAI using structured outputs

### PR DESCRIPTION
**Pull request by edwmai**
In order for structured responses to work, openai version have to be updated. Use 'pip install openai==1.47.0 --upgrade' then use 'pip freeze' to double check the right version was installed.

The current structure for the output is:
class ProductComparison(BaseModel):
    product1: str
    product2: str
    pros_product1: list[str]
    pros_product2: list[str]
    cons_product1: list[str]
    cons_product2: list[str]
    comparison_summary: str

An example comparison would look like:
{
  "comparison": {
    "product1": "Logitech G PRO X Superlight 2 Lightspeed Wireless Gaming Mouse",
    "product2": "Razer Viper V3 Pro - Ultra-lightweight Wireless Esports Gaming Mouse",
    "pros_product1": [
      "Lower price point of $147.49 with free shipping.",
      "Well-established brand with positive reviews."
    ],
    "pros_product2": [
      "Stylish white design with a dedicated esports focus.",
      "Includes additional warranty options up to 3 years."
    ],
    "cons_product1": [
      "Limited color options available (only Black).",
      "Free shipping but slightly slower estimated delivery (2-4 days)."
    ],
    "cons_product2": [
      "Higher price point of $144.99 and potentially longer international shipping time.",
      "Risk of international shipping delays and customs fees."
    ],
    "comparison_summary": "The Logitech G PRO X Superlight 2 offers a great balance of performance and price, making it a good choice for general gaming and consistent reliability, especially from a well-regarded reseller like Newegg. It is black, may take 2-4 days for delivery. Meanwhile, the Razer Viper V3 boasts a sleek design tailored for esports, along with flexible warranty options and a slightly higher price and potential shipping delays via international customs. Choose Logitech for value and brand assurance, or Razer for design and support options."
  }
}

### CODE REVIEW

**Comment by dscottd7** [comment]
@edwmai – This is great. I love the structure decisions you made here, breaking it into pros and cons.

A minor suggestion:  I would suggest updating the requirements.txt to specify the version of OpenAI required to perform this rather than installing separately. I doubt the newer version creates any backward compatibility issues for what we are doing, but that would be something to test out and validate.

**Comment by dscottd7** [comment]
@edwmai – Just remembered something you should definitely include: **comparison title**.  One of the structured components should be the title of the comparison.

Maybe another component should be the **date and time**, so we can display that in the results.

**Comment by jbh14** [comment]
@edwmai I went ahead and updated requirements per @dscottd7 's suggestion - I'm having some issues building our backend locally (scraping problems) so wasn't able to see everything you did in action unfortunately, but I was able to verify that simply installing the higher version you need via requirements works.

**Comment by edwmai** [comment]
I think time could be logged in the frontend side when the API comparison is completed. I think this will save a little bit resource from our backend and be a more accurate time of when the comparison is actually completed.

**Comment by edwmai** [comment]
TITLE is now included in the structured response. Had to name it "brief_comparison_title" to get the desired output.

**Review by dscottd7 — APPROVED** [review]
Thanks for making that change. Looks good.

**Pull request merged**
