### PR TITLE
Added selenium method to set up a headless Chrome browser for scraping

### PR DESCRIPTION
**Pull request by superhermione**
- requirements.txt is modified, so run:
```
pip install -r requirements.txt
```
- Install selenium and webdriver_manager

```
   pip install selenium
   pip install webdriver-manager
```
- Then you can run regular commend to start the program.
- After you start the frontend, you will see pop-up empty screens when the backend processing links with DevTools. This can be observed on the terminal messages.

### CODE REVIEW

**Review by dscottd7 — COMMENTED** [review]
This looks good and works great!

A few questions:

1. If we are running `pip install webdriver-manager`, is there any reason that can't be included in `requirements.txt` and installed from there (along with `selenium`)? Would be great to reduce the number of independent commands we need to run.
2. I noticed that when you declare `def compare_urls(urls: URLRequest, user_input: UserInput)`, you don't declare that as an `async` function, and when you call `get_with_selenium(str(urls.url1))`, you also don't call that as an `async` function. Is that intentional (required) not to call them asynchronously, or was that simply following the pattern Edward had established on that branch when he changed `get_with_playwright()` to be synchronous? If they can be async, that is probably a better practice.

**Comment by jbh14** [comment]
@superhermione agreed with Scott here - in fact, I pulled down your changes, added `webdriver-manager` to `requirements.txt`, and was able to get everything working without having to run `pip install webdriver-manager`

Also, a small thing, but in the updated section of the `README`, you should be having users activate the virtual environment _before_ installing requirements
- further > would you like to just replace the first section of the `README` with the new instructions?  I get the temptation to "hoard" old stuff, but GitHub makes it easy to retrieve old versions if we need to
- If you want to leave the README, I plan to issue a PR right after this gets approved as well, so would be happy to address there 

Otherwise, agreed with Scott, looks great!

**Comment by superhermione** [comment]
@jbh14 @dscottd7  

- Modified the function for compare_urls as async. Selenium doesn’t support native async operations. To make it synchronous, asyncio.run_in_executor() is used. 
- I also added modified the prompt_service to add requesting a comparison title for the opena call. 
- Updated README (just some clean up, not too much changes).

**Comment by jbh14** [comment]
Nice @superhermione !  I just pulled down and re-tested, looking good

**Pull request merged**
