### PR TITLE
Websocket implementation to reduce latency

### PR DESCRIPTION
**Pull request by dscottd7**
This branch is meant to be run with the `websockets` branch on the frontend. Changes here include 

- making a websocket connection with the frontend instead of an HTTP request
- scraping the two URLs concurrently through async processes
- creating a comparison_manager to handle all of the async tasks and communicate with frontend
- creating a selenium_pool object to be able to have multiple concurrent Chrome drivers operating
- handling of messages back and forth between frontend and backend throughout the comparison process

### CODE REVIEW

**Review by superhermione — COMMENTED** [review]
This is organized and the  logger messages are more informative. I tested it with both swagger and frontend, I don't see any issues.

**Comment by jbh14** [comment]
Confirmed with everyone on the call that this is good - merging into main

**Review by jbh14 — APPROVED** [review]
Confirmed with everyone on the call that this is good - merging into main

**Review by edwmai — APPROVED** [review]
I like that you abstracted the websocket endpoint implementation making the endpoints.py file cleaner. I also like the fact that the websocket endpoints are implemented in a way that the http endpoints are also working, just in case we want to use http request instead.

**Pull request merged**
